stages:
    - build

variables:
  CONTAINER_RELEASE_API: "docker-registry.beta.innovation.insee.eu/hadrilec/graffiti-env"

package:
  # Use stage build here, so the pages job may later pickup the created site.
  stage: build
  tags:
    - maven
  script:
    - 'docker build -t $CONTAINER_RELEASE_API .'
    - 'docker push $CONTAINER_RELEASE_API'
  only:
    - master@hadrilec/graffiti-env
